export const productsFake = [
    {
        'id': 1,
        'title': 'Zeus Smart Visor',
        'slug': 'zeus-smart-visor1',
        'price': 1000.00,
        'short_description': 'Descubra uma experiência de fumar envolvente com nossa seleção premium de narguilés. Originado no Oriente Médio, este dispositivo de água oferece uma abordagem única e social para apreciar tabacos aromatizados. Com designs elegantes, qualidade excepcional e uma variedade de sabores exclusivos, nossos narguilés proporcionam momentos relaxantes e compartilháveis entre amigos. Explore a tradição e a modernidade, escolhendo entre nossa variedade de modelos, cada um projetado para elevar sua experiência de fumar. Encontre o narguilé perfeito para expressar seu estilo e desfrute de momentos de descontração inesquecíveis. Transforme sua experiência de fumar com a qualidade e a sofisticação que você merece.',
        'description': 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minus, praesentium, possimus mollitia eveniet aut dolore odio porro id natus voluptatibus temporibus illo, neque maxime a quas non ea sequi laborum. Dolor ad quia soluta consequuntur, minima corrupti molestiae atque placeat animi dicta itaque quibusdam minus eos velit, optio in nostrum ullam laborum est illo ipsum assumenda saepe. Laborum velit facilis fuga voluptatum quisquam iusto, cum, dolores, ipsa vel unde corrupti nisi exercitationem. Tempora veritatis molestiae modi quidem dignissimos totam porro, eligendi eveniet sunt ut animi illo fugit voluptatum cupiditate praesentium reprehenderit inventore, adipisci obcaecati maiores qui autem ad perferendis! Soluta totam recusandae illo maiores laborum modi fuga, dicta tempore magnam molestiae obcaecati nemo culpa beatae similique et. Porro, ad doloribus consectetur consequuntur enim commodi nulla obcaecati blanditiis ea aut corporis adipisci quisquam! Ex, cupiditate laborum eaque eveniet praesentium tenetur molestiae dolor vero eius reiciendis est et illo expedita ipsum aliquid perspiciatis! Quod commodi in cum, iusto ratione enim voluptatum nesciunt rem omnis nihil, vitae natus. Ad mollitia exercitationem inventore aliquid eum harum ratione rerum quisquam aspernatur fugiat nulla magnam esse, veritatis rem cupiditate odit beatae quo cumque enim dolorum eveniet vitae dignissimos. Adipisci neque sapiente suscipit quaerat molestiae molestias minus?',
        'image': '/zeus-smart.jpg',
        'brand': 'Zeus',
        'model': 'Smart',
        'colors': ['Preto', 'Gold', 'Prata', 'Rosa'],
        'defaultCategory': {nome: 'Narguile', image: '/narguile.svg'},
        'categories': ['Shishas', 'Lorem Ipsum'],
        'quantity': 4,
        'status': 'active',
        'created_at': new Date('2021-01-01T00:00:00'),
        'updated_at': new Date('2021-01-01T00:00:00'),
        'deleted_at': null,
        'height': 70,
        'width': 20,
        'length': 20,
        'weight': 10,
        'material': 'Aço',
        'country': 'Brasil',
        'products_related': [2,3,4,7]
    },
    {
        'id': 2,
        'title': 'Regal Hookah',
        'slug': 'regal-hookah',
        'price': 1400.00,
        'short_description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, quam libero aliquet nunc, nec ultricies nisl nunc nec nunc.',
        'image': '/regal.jpg',
        'brand': 'Regal',
        'model': 'Regal',
        'colors': ['Azul', 'Gold'],
        'defaultCategory': {nome: 'Narguile', image: '/narguile.svg'},
        'categories': ['Shishas', 'Lorem Ipsum'],
        'quantity': 4,
        'status': 'active',
        'created_at': new Date('2021-01-01T00:00:00'),
        'updated_at': new Date('2021-01-01T00:00:00'),
        'deleted_at': null,
        'height': 70,
        'width': 20,
        'length': 20,
        'weight': 10,
        'material': 'Aço',
        'country': 'Brasil',
        'products_related': [1,3,4,7]
    },
    {
        'id': 3,
        'title': 'Triton Zip',
        'slug': 'triton-zip',
        'price': 400.00,
        'short_description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, quam libero aliquet nunc, nec ultricies nisl nunc nec nunc.',
        'image': '/triton.jpg',
        'brand': 'Triton',
        'model': 'Zip',
        'colors': ['Preto', 'Gold'],
        'defaultCategory': {nome: 'Narguile', image: '/narguile.svg'},
        'categories': ['Shishas', 'Lorem Ipsum'],
        'quantity': 4,
        'status': 'active',
        'created_at': new Date('2021-01-01T00:00:00'),
        'updated_at': new Date('2021-01-01T00:00:00'),
        'deleted_at': null,
        'height': 70,
        'width': 20,
        'length': 20,
        'weight': 10,
        'material': 'Aço',
        'country': 'Brasil',
        'products_related': [1,3,4,7]
    },
    {
        'id': 4,
        'title': 'Zeus Smart Visor',
        'slug': 'zeus-smart-visor4',
        'price': 1000.00,
        'short_description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, quam libero aliquet nunc, nec ultricies nisl nunc nec nunc.',
        'image': '/zeus-smart.jpg',
        'brand': 'Zeus',
        'model': 'Smart',
        'colors': ['Preto', 'Gold'],
        'defaultCategory': {nome: 'Narguile', image: '/narguile.svg'},
        'categories': ['Shishas', 'Lorem Ipsum'],
        'quantity': 4,
        'status': 'active',
        'created_at': new Date('2021-01-01T00:00:00'),
        'updated_at': new Date('2021-01-01T00:00:00'),
        'deleted_at': null,
        'height': 70,
        'width': 20,
        'length': 20,
        'weight': 10,
        'material': 'Aço',
        'country': 'Brasil',
        'products_related': [1,3,4,7]
    },
    {
        'id': 5,
        'title': 'Zeus Smart Visor',
        'slug': 'zeus-smart-visor5',
        'price': 1000.00,
        'short_description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, quam libero aliquet nunc, nec ultricies nisl nunc nec nunc.',
        'image': '/zeus-smart.jpg',
        'brand': 'Zeus',
        'model': 'Smart',
        'colors': ['Preto', 'Gold'],
        'defaultCategory': {nome: 'Narguile', image: '/narguile.svg'},
        'categories': ['Shishas', 'Lorem Ipsum'],
        'quantity': 4,
        'status': 'active',
        'created_at': new Date('2021-01-01T00:00:00'),
        'updated_at': new Date('2021-01-01T00:00:00'),
        'deleted_at': null,
        'height': 70,
        'width': 20,
        'length': 20,
        'weight': 10,
        'material': 'Aço',
        'country': 'Brasil',
        'products_related': [1,3,4,7]
    },
    {
        'id': 6,
        'title': 'Zeus Smart Visor',
        'slug': 'zeus-smart-visor6',
        'price': 1000.00,
        'short_description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, quam libero aliquet nunc, nec ultricies nisl nunc nec nunc.',
        'image': '/zeus-smart.jpg',
        'brand': 'Zeus',
        'model': 'Smart',
        'colors': ['Preto', 'Gold'],
        'defaultCategory': {nome: 'Narguile', image: '/narguile.svg'},
        'categories': ['Shishas', 'Lorem Ipsum'],
        'quantity': 4,
        'status': 'active',
        'created_at': new Date('2021-01-01T00:00:00'),
        'updated_at': new Date('2021-01-01T00:00:00'),
        'deleted_at': null,
        'height': 70,
        'width': 20,
        'length': 20,
        'weight': 10,
        'material': 'Aço',
        'country': 'Brasil',
        'products_related': [1,3,4,7]
    },
    {
        'id': 7,
        'title': 'Zeus Smart Visor',
        'slug': 'zeus-smart-visor7',
        'price': 1000.00,
        'short_description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, quam libero aliquet nunc, nec ultricies nisl nunc nec nunc.',
        'image': '/zeus-smart.jpg',
        'brand': 'Zeus',
        'model': 'Smart',
        'colors': ['Preto', 'Gold'],
        'defaultCategory': {nome: 'Narguile', image: '/narguile.svg'},
        'categories': ['Shishas', 'Lorem Ipsum'],
        'quantity': 4,
        'status': 'active',
        'created_at': new Date('2021-01-01T00:00:00'),
        'updated_at': new Date('2021-01-01T00:00:00'),
        'deleted_at': null,
        'height': 70,
        'width': 20,
        'length': 20,
        'weight': 10,
        'material': 'Aço',
        'country': 'Brasil',
        'products_related': [2,3,4,7]
    },
    {
        'id': 8,
        'title': 'Zeus Smart Visor',
        'slug': 'zeus-smart-visor8',
        'price': 1000.00,
        'short_description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, quam libero aliquet nunc, nec ultricies nisl nunc nec nunc.',
        'image': '/zeus-smart.jpg',
        'brand': 'Zeus',
        'model': 'Smart',
        'colors': ['Preto', 'Gold'],
        'defaultCategory': {nome: 'Narguile', image: '/narguile.svg'},
        'categories': ['Shishas', 'Lorem Ipsum'],
        'quantity': 4,
        'status': 'active',
        'created_at': new Date('2021-01-01T00:00:00'),
        'updated_at': new Date('2021-01-01T00:00:00'),
        'deleted_at': null,
        'height': 70,
        'width': 20,
        'length': 20,
        'weight': 10,
        'material': 'Aço',
        'country': 'Brasil',
        'products_related': [1,3,4,7]
    },
    {
        'id': 9,
        'title': 'Zeus Smart Visor',
        'slug': 'zeus-smart-visor9',
        'price': 1000.00,
        'short_description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, quam libero aliquet nunc, nec ultricies nisl nunc nec nunc.',
        'image': '/zeus-smart.jpg',
        'brand': 'Zeus',
        'model': 'Smart',
        'colors': ['Preto', 'Gold'],
        'defaultCategory': {nome: 'Narguile', image: '/narguile.svg'},
        'categories': ['Shishas', 'Lorem Ipsum'],
        'quantity': 4,
        'status': 'active',
        'created_at': new Date('2021-01-01T00:00:00'),
        'updated_at': new Date('2021-01-01T00:00:00'),
        'deleted_at': null,
        'height': 70,
        'width': 20,
        'length': 20,
        'weight': 10,
        'material': 'Aço',
        'country': 'Brasil',
        'products_related': [1,3,4,7]
    },
    {
        'id': 10,
        'title': 'Zeus Smart Visor',
        'slug': 'zeus-smart-visor10',
        'price': 1000.00,
        'short_description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, quam libero aliquet nunc, nec ultricies nisl nunc nec nunc.',
        'image': '/zeus-smart.jpg',
        'brand': 'Zeus',
        'model': 'Smart',
        'colors': ['Preto', 'Gold'],
        'defaultCategory': {nome: 'Narguile', image: '/narguile.svg'},
        'categories': ['Shishas', 'Lorem Ipsum'],
        'quantity': 4,
        'status': 'active',
        'created_at': new Date('2021-01-01T00:00:00'),
        'updated_at': new Date('2021-01-01T00:00:00'),
        'deleted_at': null,
        'height': 70,
        'width': 20,
        'length': 20,
        'weight': 10,
        'material': 'Aço',
        'country': 'Brasil',
        'products_related': [1,3,4,7]
    },
    {
        'id': 11,
        'title': 'Zeus Smart Visor',
        'slug': 'zeus-smart-visor11',
        'price': 1000.00,
        'short_description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, quam libero aliquet nunc, nec ultricies nisl nunc nec nunc.',
        'image': '/zeus-smart.jpg',
        'brand': 'Zeus',
        'model': 'Smart',
        'colors': ['Preto', 'Gold'],
        'defaultCategory': {nome: 'Narguile', image: '/narguile.svg'},
        'categories': ['Shishas', 'Lorem Ipsum'],
        'quantity': 4,
        'status': 'active',
        'created_at': new Date('2021-01-01T00:00:00'),
        'updated_at': new Date('2021-01-01T00:00:00'),
        'deleted_at': null,
        'height': 70,
        'width': 20,
        'length': 20,
        'weight': 10,
        'material': 'Aço',
        'country': 'Brasil',
        'products_related': [1,3,4,7]
    },
    {
        'id': 12,
        'title': 'Zeus Smart Visor',
        'slug': 'zeus-smart-visor12',
        'price': 1000.00,
        'short_description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, quam libero aliquet nunc, nec ultricies nisl nunc nec nunc.',
        'image': '/zeus-smart.jpg',
        'brand': 'Zeus',
        'model': 'Smart',
        'colors': ['Preto', 'Gold'],
        'defaultCategory': {nome: 'Narguile', image: '/narguile.svg'},
        'categories': ['Shishas', 'Lorem Ipsum'],
        'quantity': 4,
        'status': 'active',
        'created_at': new Date('2021-01-01T00:00:00'),
        'updated_at': new Date('2021-01-01T00:00:00'),
        'deleted_at': null,
        'height': 70,
        'width': 20,
        'length': 20,
        'weight': 10,
        'material': 'Aço',
        'country': 'Brasil',
        'products_related': [1,3,4,7]
    }
]